const $=s=>document.querySelector(s);const roomCodeEl=$('#roomCode'),joinCode=$('#joinCode'),joinBtn=$('#joinBtn'),newRoomBtn=$('#newRoomBtn'),copyBtn=$('#copyCodeBtn'),fileInput=$('#fileInput'),dropZone=$('#dropZone'),filePanel=$('#filePanel'),fileList=$('#fileList'),transferPanel=$('#transferPanel'),transferName=$('#transferName'),transferMeta=$('#transferMeta'),transferPercent=$('#transferPercent'),progressBar=$('#progressBar'),transferAmount=$('#transferAmount'),transferSpeed=$('#transferSpeed'),transferState=$('#transferState'),roleLabel=$('#roleLabel'),roomMessage=$('#roomMessage'),pill=$('#connectionPill'),toast=$('#toast');
const SIGNALING_URL=(location.hostname==='localhost'||location.hostname==='127.0.0.1')?'ws://localhost:8787':(location.protocol==='https:'?'wss://'+location.host.replace(/:\d+$/,'')+'/ws':'ws://'+location.host+'/ws');
const ICE={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]};let ws=null,pc=null,dc=null,room='',isSender=false,files=[],currentFile=null,receivedChunks=[],receivedBytes=0,expectedBytes=0,lastTime=0,lastBytes=0;
function toastMsg(m){toast.textContent=m;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),2300)}
function setStatus(ok,text){pill.classList.toggle('connected',ok);pill.querySelector('span').textContent=text}
function formatBytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return `${(n/Math.pow(1024,i)).toFixed(i?1:0)} ${u[i]}`}
function randomCode(){return String(Math.floor(100000+Math.random()*900000))}
function showRoom(c){room=c;roomCodeEl.textContent=c}
function connectWS(){if(ws&&ws.readyState<=1)return;ws=new WebSocket(SIGNALING_URL);ws.onopen=()=>{setStatus(false,'Signaling ready');if(room)send({type:'create',room})};ws.onclose=()=>setStatus(false,'Disconnected');ws.onerror=()=>roomMessage.textContent='Signaling server से connection नहीं बन पाया।'}
function send(x){if(ws?.readyState===1)ws.send(JSON.stringify(x))}
function initRoom(){room=randomCode();showRoom(room);isSender=true;roleLabel.textContent='SENDER';filePanel.classList.remove('disabled-panel');roomMessage.textContent='अब इस code को दूसरे device पर खोलकर डालें।';resetTransfer();connectWS()}
function resetTransfer(){transferPanel.classList.add('hidden');fileList.innerHTML='';files=[];fileInput.value=''}
function setupPC(initiator){pc=new RTCPeerConnection(ICE);pc.onicecandidate=e=>{if(e.candidate)send({type:'candidate',candidate:e.candidate})};pc.onconnectionstatechange=()=>{const s=pc.connectionState;if(s==='connected'){setStatus(true,'Connected');roomMessage.textContent='🟢 दूसरा device connected है।';toastMsg('Device connected');filePanel.classList.remove('disabled-panel')}else if(['failed','disconnected','closed'].includes(s)){setStatus(false,s);}};if(initiator){dc=pc.createDataChannel('files');setupDC();}else pc.ondatachannel=e=>{dc=e.channel;setupDC()}}
function setupDC(){dc.binaryType='arraybuffer';dc.onopen=()=>{setStatus(true,'Connected');roomMessage.textContent='🟢 Live transfer connection ready';if(isSender&&files.length)sendFileQueue()};dc.onclose=()=>setStatus(false,'Channel closed');dc.onmessage=e=>receiveMessage(e.data)}
async function makeOffer(){setupPC(true);const offer=await pc.createOffer();await pc.setLocalDescription(offer);send({type:'offer',sdp:pc.localDescription})}
async function receiveMessage(data){if(typeof data==='string'){const m=JSON.parse(data);if(m.kind==='meta'){currentFile={name:m.name,size:m.size,type:m.type};receivedChunks=[];receivedBytes=0;expectedBytes=m.size;startTransferUI(m.name,m.size,'RECEIVING');return}if(m.kind==='end'){const blob=new Blob(receivedChunks,{type:currentFile.type||'application/octet-stream'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=currentFile.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);transferState.textContent='COMPLETE';updateProgress(expectedBytes,expectedBytes);toastMsg('File received successfully');return}}else{receivedChunks.push(data);receivedBytes+=data.byteLength;updateProgress(receivedBytes,expectedBytes)}}
function startTransferUI(name,size,state){transferPanel.classList.remove('hidden');transferName.textContent=name;transferMeta.textContent=formatBytes(size);transferState.textContent=state;progressBar.style.width='0%';transferPercent.textContent='0%';transferAmount.textContent=`0 B / ${formatBytes(size)}`;lastTime=performance.now();lastBytes=0}
function updateProgress(done,total){const p=total?Math.min(100,done/total*100):0;progressBar.style.width=p+'%';transferPercent.textContent=Math.floor(p)+'%';transferAmount.textContent=`${formatBytes(done)} / ${formatBytes(total)}`;const now=performance.now();if(now-lastTime>300){const speed=(done-lastBytes)/((now-lastTime)/1000);transferSpeed.textContent=formatBytes(speed)+'/s';lastTime=now;lastBytes=done}}
async function sendFileQueue(){for(const f of files){currentFile=f;startTransferUI(f.name,f.size,'SENDING');send({kind:'meta',name:f.name,size:f.size,type:f.type});const chunk=64*1024;let offset=0;while(offset<f.size){if(dc.readyState!=='open')throw Error('Connection closed');while(dc.bufferedAmount>4*1024*1024)await new Promise(r=>setTimeout(r,20));const buf=await f.slice(offset,offset+chunk).arrayBuffer();dc.send(buf);offset+=buf.byteLength;updateProgress(offset,f.size);await new Promise(r=>setTimeout(r,0))}send({kind:'end'});transferState.textContent='COMPLETE';toastMsg(`${f.name} sent`)} }
fileInput.addEventListener('change',()=>{files=[...fileInput.files];renderFiles();if(files.length&&dc?.readyState==='open')sendFileQueue()});dropZone.addEventListener('dragover',e=>{e.preventDefault();dropZone.classList.add('drag')});dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('drag'));dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.classList.remove('drag');files=[...e.dataTransfer.files];renderFiles();if(files.length&&dc?.readyState==='open')sendFileQueue()});function renderFiles(){fileList.innerHTML=files.map(f=>`<div class="file-item"><div class="fi">📄</div><div style="min-width:0;flex:1"><b>${escapeHtml(f.name)}</b><span>${formatBytes(f.size)}</span></div></div>`).join('');if(files.length){transferPanel.classList.remove('hidden');transferName.textContent=files[0].name;transferMeta.textContent=formatBytes(files[0].size);transferState.textContent=dc?.readyState==='open'?'READY':'WAITING'}}function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
newRoomBtn.onclick=initRoom;copyBtn.onclick=async()=>{if(room&&room!=='------'){await navigator.clipboard.writeText(room);toastMsg('Code copied')}};joinBtn.onclick=()=>{const c=joinCode.value.replace(/\D/g,'').slice(0,6);if(c.length!==6)return toastMsg('6-digit code डालें');room=c;isSender=false;roleLabel.textContent='RECEIVER';roomCodeEl.textContent=c;roomMessage.textContent='Room खोज रहे हैं…';filePanel.classList.remove('disabled-panel');connectWS();setTimeout(()=>send({type:'join',room}),300)};joinCode.addEventListener('input',()=>joinCode.value=joinCode.value.replace(/\D/g,'').slice(0,6));
if(!room)initRoom();
ws?.addEventListener('message',async()=>{});function handleSignal(msg){ }
// Rebind WS message handler through property assignment after socket creation.
const oldConnect=connectWS;connectWS=function(){if(ws&&ws.readyState<=1)return;ws=new WebSocket(SIGNALING_URL);ws.onopen=()=>{setStatus(false,'Signaling ready');if(isSender)send({type:'create',room});else send({type:'join',room})};ws.onclose=()=>setStatus(false,'Disconnected');ws.onerror=()=>roomMessage.textContent='Signaling server से connection नहीं बन पाया।';ws.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='room-created'){roomMessage.textContent='Waiting for दूसरे device…';return}if(m.type==='peer-joined'){roomMessage.textContent='Device मिला, connection बना रहे हैं…';await makeOffer();return}if(m.type==='offer'){setupPC(false);await pc.setRemoteDescription(m.sdp);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);send({type:'answer',sdp:pc.localDescription});return}if(m.type==='answer'){await pc.setRemoteDescription(m.sdp);return}if(m.type==='candidate'){try{await pc.addIceCandidate(m.candidate)}catch(err){console.warn(err)}}if(m.type==='error'){toastMsg(m.message)}}};
// Reinitialize cleanly with the final connectWS implementation.
ws=null;initRoom();
